# Site settings
title: "Romaric Drigon"
email: romaric.drigon@gmail.com
description: |-
    Software engineer and trainer at [netinfluence](https://netinfluence.ch) in Lausanne, Switzerland.
    Interested in all things Symfony related ; devops ; web development.
    Symfony certified expert, consultant.
    Available for contracts.
url: "https://romaricdrigon.github.io/"
baseurl: "" # the subpath of your site
show_excerpts: true
excerpt_separator: "<!-- more-->"
permalink: /:year/:month/:day/:title
timezone: 'Europe/Zurich'

# Build settings
markdown: kramdown
theme: minima
plugins: # Github Pages plugins we are using
    - jekyll-feed
    - jekyll-sitemap

# Exclude from processing. Default values below.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Feed plugin - we have an extra feed for Symfony Posts
feed:
  categories:
    - symfony

# Theme settings
twitter_username: romaricdrigon
github_username: romaricdrigon
linkedin_username: romaricdrigon
rss: RSS feed
minima:
    date_format: "%d/%m/%Y %H:%M"
