# Site settings
title: "Romaric Drigon"
email: romaric.drigon@gmail.com
description: |-
    Software engineer and trainer at [netinfluence](https://netinfluence.ch) in Lausanne, Switzerland.
    Interested in all things Symfony related ; devops ; web development.
    Symfony certified expert, consultant.
    Available for contracts.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://romaricdrigon.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
show_excerpts: true
permalink: /:year/:month/:day/:title
timezone: 'Europe/Zurich'

# Build settings
markdown: kramdown
theme: minima
plugins:
    - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Theme settings
twitter_username: romaricdrigon
github_username: romaricdrigon
linkedin_username: romaricdrigon
rss: RSS feed
minima:
    date_format: "%d/%m/%Y %H:%M"
